# -*- coding: utf-8 -*-

# This code is part of Qiskit.
#
# (C) Copyright IBM 2019, 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""common methods for sub-interfaces within Qiskit Optimization"""

from abc import ABC
from typing import Callable, Sequence, Union, Any, List, Generator

from qiskit.optimization.utils.helpers import NameIndex
from qiskit.optimization.utils.qiskit_optimization_error import QiskitOptimizationError


class BaseInterface(ABC):
    """
    Abstract class with common methods
    for sub-interfaces within Qiskit Optimization.
    """

    def __init__(self):
        """Creates a new BaseInterface.

        This class is not meant to be instantiated directly nor used
        externally.
        """
        self._index = NameIndex()

    def get_indices(self, *name) -> Union[int, List[int]]:
        """Converts from names to indices.

        If name is a string, get_indices returns the index of the
        object with that name.  If no such object exists, an
        exception is raised.

        If name is a sequence of strings, get_indices returns a list
        of the indices corresponding to the strings in name.
        Equivalent to map(self.get_indices, name).

        See `NameIndex.convert` for details.

        If the subclass does not provide an index function (i.e., the
        interface is not indexed), then a NotImplementedError is raised.

        Example usage:

        >>> from qiskit.optimization import QuadraticProgram
        >>> op = QuadraticProgram()
        >>> indices = op.variables.add(names=["a", "b"])
        >>> op.variables.get_indices("a")
        0
        >>> op.variables.get_indices(["a", "b"])
        [0, 1]
        """
        return self._index.convert(*name)

    @staticmethod
    def _setter(setfunc: Callable[[Union[str, int], Any], None], *args) -> None:
        """A generic setter method

        Args:
            setfunc: A setter function of two parameters: `index` and `val`.
                Since `index` can be a string, users need to convert it into an appropriate index
                by applying `NameIndex.convert`.
            *args: A pair of index and value or a list of pairs of index and value.
                `setfunc` is invoked with `args`.

        Raises:
            QiskitOptimizationError: Invalid arguments
        """
        # check for all elements in args whether they are types
        if len(args) == 1 and isinstance(args[0], (Sequence, Generator)):
            arg0 = list(args[0]) if isinstance(args[0], Generator) else args[0]
            if all(isinstance(pair, Sequence) and len(pair) == 2 for pair in arg0):
                for pair in arg0:
                    setfunc(*pair)
            else:
                raise QiskitOptimizationError("Invalid arguments: {}".format(args))
        elif len(args) == 2:
            setfunc(*args)
        else:
            raise QiskitOptimizationError("Invalid arguments: {}".format(args))

    @staticmethod
    def _getter(getfunc: Callable[[int], Any], *args) -> Any:
        """A generic getter method

        Args:
            getfunc(index): A getter function with an argument `index`.
                `index` should be already converted by `NameIndex.convert`.
            *args: A single index or a list of indices. `getfunc` is invoked with args.

        Returns:
            Union[int, List[int]]: if `args` is a single index, this returns a single
                                    value generated by `getfunc`. If `args` is a list of indices,
                                    this returns a list of values.

        Raises:
            QiskitOptimizationError: Invalid arguments
        """
        if len(args) == 0:
            raise QiskitOptimizationError('Empty arguments should be handled in the caller')
        if len(args) == 1:
            if isinstance(args[0], Sequence):
                args = args[0]
            else:
                return getfunc(args[0])
        return [getfunc(k) for k in args]
