# This code is part of Qiskit.
#
# (C) Copyright IBM 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Qiskit Aqua'
description: 'Installs Qiskit Aqua on developer mode'

runs:
  using: "composite"
  steps: 
    - run : |
        if [ -f "$HOME/miniconda/etc/profile.d/conda.sh" ]; then
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda activate
        fi
        pip install -e .
        pip install -U -c constraints.txt -r requirements-dev.txt
      shell: bash